### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by richardjs** [borwick/tdapi#1]
Hello! I'm working on TeamDynamix integration for my employer, and started writing a Python API before deciding to search for existing ones. I might like to use/contribute to/fork this project depending on how our requirements go. Is it possible for you to release the code under a license?

Thanks!

**Comment by borwick** [comment]
For sure! [License added](https://github.com/borwick/tdapi/commit/dc641c1f18fc0d0c1ffcdff834c1fe73447672dd).

**Comment by richardjs** [comment]
Thanks!
